//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// This file was autogenerated by cuetsy. DO NOT EDIT!
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

import * as ui from '@grafana/schema';

export const modelVersion = Object.freeze([0, 0]);

export interface PanelOptions extends ui.OptionsWithLegend, ui.OptionsWithTooltip, ui.OptionsWithTextFormatting {
  barWidth: number;
  groupWidth: number;
  orientation: ui.VizOrientation;
  showValue: ui.VisibilityMode;
  stacking: string;
}

export const defaultPanelOptions: PanelOptions = {
  stacking: 'none',
};

export interface PanelFieldConfig extends ui.AxisConfig, ui.HideableFieldConfig {
  fillOpacity?: number;
  gradientMode?: string;
  lineWidth?: number;
}
