// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     SummarizerJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package check

import "github.com/grafana/grafana/pkg/kindsys"

// Summarizer returns a func that takes raw bytes representing a Check
// and constructs a [kindsys.EntitySummary].
func Summarizer() kindsys.Summarizer {
	// This func is a gateway. The generated body depends on the value of handleSummary.
	// in the Check kind declaration.

	// handleSummary is "passthrough" for the Check kind. If the Go compiler
	// is failing here, you must either hand-implement getSummarizer() in another file in
	// this package, or change the value of handleSummary to "generic".
	return getSummarizer()
}
