// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     GoTypesJenny
//     LatestJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package check

// Defines values for Type.
const (
	TypeDns Type = "dns"

	TypeHttp Type = "http"

	TypePing Type = "ping"

	TypeTcp Type = "tcp"
)

// Check defines model for check.
type Check struct {
	Job       string   `json:"job"`
	Locations []string `json:"locations"`
	Target    string   `json:"target"`
	Type      Type     `json:"type"`
	Uid       string   `json:"uid"`
}

// Type defines model for Check.Type.
type Type string
