// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     GoTypesJenny
//     LatestJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package check

// Defines values for Type.
const (
	TypeDns Type = "dns"

	TypeHttp Type = "http"

	TypePing Type = "ping"

	TypeTcp Type = "tcp"
)

// Check defines model for check.
type Check struct {
	Job string `json:"job"`

	// hack this in body b/c kindsys doesn't support meta yet
	// codegen here is buggy - value type IS always a string, you can safely assert that in your code
	Labels    map[string]interface{} `json:"labels"`
	Locations []string               `json:"locations"`
	Target    string                 `json:"target"`
	Type      Type                   `json:"type"`
	Uid       string                 `json:"uid"`
}

// Type defines model for Check.Type.
type Type string
