// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     SummarizerJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package platformatonsm

import "github.com/grafana/grafana/pkg/kindsys"

// Summarizer returns a func that takes raw bytes representing a PlatformatonSM
// and constructs a [kindsys.EntitySummary].
func Summarizer() kindsys.Summarizer {
	// This func is a gateway. The generated body depends on the value of handleSummary.
	// in the PlatformatonSM kind declaration.

	// handleSummary is "generic" for the PlatformatonSM kind. The generic summary
	// extractor is used.
	return kindsys.GenericSummarizer("PlatformatonSM")
}
