// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     TSTypesJenny
//     LatestMajorsOrXJenny
//
// Run 'make gen-cue' from repository root to regenerate.

export interface Check {
  job: string;
  /**
   * hack this in body b/c kindsys doesn't support meta yet
   * codegen here is buggy - value type IS always a string, you can safely assert that in your code
   */
  labels: Record<string, unknown>;
  locations: Array<string>;
  target: string;
  type: ('http' | 'ping' | 'dns' | 'tcp');
  uid: string;
}

export const defaultCheck: Partial<Check> = {
  locations: [],
};
