// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     TSTypesJenny
//     LatestMajorsOrXJenny
//
// Run 'make gen-cue' from repository root to regenerate.

export interface Check {
  job: string;
  locations: Array<string>;
  target: string;
  type: ('http' | 'ping' | 'dns' | 'tcp');
  uid: string;
}

export const defaultCheck: Partial<Check> = {
  locations: [],
};
