// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     GoTypesJenny
//     LatestJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package service

// Defines values for EndpointsType.
const (
	EndpointsTypeDns EndpointsType = "dns"

	EndpointsTypeHttp EndpointsType = "http"

	EndpointsTypePing EndpointsType = "ping"

	EndpointsTypeTcp EndpointsType = "tcp"
)

// Defines values for EndpointType.
const (
	EndpointTypeDns EndpointType = "dns"

	EndpointTypeHttp EndpointType = "http"

	EndpointTypePing EndpointType = "ping"

	EndpointTypeTcp EndpointType = "tcp"
)

// Service defines model for service.
type Service struct {
	Endpoints []struct {
		Path string        `json:"path"`
		Type EndpointsType `json:"type"`
	} `json:"endpoints"`

	// name of the service
	Name string `json:"name"`
	Uid  string `json:"uid"`
}

// EndpointsType defines model for Service.Endpoints.Type.
type EndpointsType string

// Endpoint defines model for service.Endpoint.
type Endpoint struct {
	Path string       `json:"path"`
	Type EndpointType `json:"type"`
}

// EndpointType defines model for Endpoint.Type.
type EndpointType string
