// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     GoTypesJenny
//     LatestJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package platformatonsm

// PlatformatonSM defines model for platformatonsm.
type PlatformatonSM struct {
	GenerateFor struct {
		Dns  bool `json:"dns"`
		Http bool `json:"http"`
		Ping bool `json:"ping"`
		Tcp  bool `json:"tcp"`
	} `json:"generateFor"`
}
