// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     TSTypesJenny
//     LatestMajorsOrXJenny
//
// Run 'make gen-cue' from repository root to regenerate.

export interface Endpoint {
  path: string;
  type: ('http' | 'ping' | 'dns' | 'tcp');
}

export interface Service {
  endpoints?: Array<Endpoint>;
  /**
   * hack this in body b/c kindsys doesn't support meta yet.
   * codegen here is buggy - value type IS always a string, you can safely assert that in your code
   */
  labels: Record<string, unknown>;
  /**
   * name of the service
   */
  name: string;
  uid: string;
}

export const defaultService: Partial<Service> = {
  endpoints: [],
};
