// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     TSTypesJenny
//     LatestMajorsOrXJenny
//
// Run 'make gen-cue' from repository root to regenerate.

export interface Platformatonsm {
  generateFor: {
    http: boolean;
    ping: boolean;
    dns: boolean;
    tcp: boolean;
  };
}
