name: "publish-technical-documentation-next"

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/sources/**"
  workflow_dispatch:
jobs:
  sync:
    if: "github.repository == 'grafana/grafana'"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Grafana repo"
        uses: "actions/checkout@v3"

      - name: "Clone website-sync Action"
        # WEBSITE_SYNC_GRAFANA is a fine-grained GitHub Personal Access Token that expires.
        # It must be updated in the grafanabot GitHub account.
        run: "git clone --single-branch --no-tags --depth 1 -b master https://grafanabot:${{ secrets.WEBSITE_SYNC_GRAFANA }}@github.com/grafana/website-sync ./.github/actions/website-sync"

      - name: "Publish to website repository (next)"
        uses: "./.github/actions/website-sync"
        id: "publish-next"
        with:
          repository: "grafana/website"
          branch: "master"
          host: "github.com"
          # PUBLISH_TO_WEBSITE_GRAFANA is a fine-grained GitHub Personal Access Token that expires.
          # It must be updated in the grafanabot GitHub account.
          github_pat: "grafanabot:${{ secrets.PUBLISH_TO_WEBSITE_GRAFANA }}"
          source_folder: "docs/sources"
          target_folder: "content/docs/grafana/next"
