//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// This file was autogenerated by cuetsy. DO NOT EDIT!
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

import * as ui from '@grafana/schema';

export const modelVersion = Object.freeze([0, 0]);

export interface PanelOptions {
  frameIndex: number;
  showHeader: boolean;
  showTypeIcons: boolean;
  sortBy?: ui.TableSortByFieldState[];
}

export const defaultPanelOptions: PanelOptions = {
  frameIndex: 0,
  showHeader: true,
  showTypeIcons: false,
};

export interface PanelFieldConfig {
  align?: string;
  displayMode?: string;
  filterable?: boolean;
  minWidth?: number;
  width?: number;
}

export const defaultPanelFieldConfig: PanelFieldConfig = {
  align: 'auto',
  displayMode: 'auto',
};
